# Generated by Django 2.1.5 on 2019-02-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingjobs',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'process'), (1, 'success'), (2, 'failure')], default=0, verbose_name='status'),
        ),
    ]
