# Generated by Django 2.1.5 on 2019-02-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedvideo',
            name='duration',
            field=models.CharField(max_length=12, verbose_name='duration'),
        ),
    ]
